
result = 1 + 2
print('result =',result)
result = 3
original_result = result
result = result + 1
print('result =',result)
result = 4
result = result - 1
print('result =',result)
result = 3
original_result = result
result = result * 2
original_result = result
print('result =',result)
result = 6
result = result ** 3
original_result = result
print('result =',result)
result = 216
result = result + 8
original_result = result
print('result =',result)
result = 224
result = result % 7
original_result = result
print('result =',result)
result = 0
result = result // 2
original_result = result
print('result =',result)
result = 0